image: docker:19.03.0
services:
  - name: docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
 - offline-chkk

chkk-manifest-job:
  stage: offline-chkk
  before_script:
    - apk add curl
    - curl -Lo chkk https://downloads.chkk.dev/v0.0.1/chkk-linux-amd64
    - export CHKK_ACCESS_TOKEN=$CHKK_ACCESS_TOKEN
    - chmod +x chkk
    - ./chkk standalone install -p $endpoint_port
    - while true; do nc -zv docker $endpoint_port && break || sleep 5; done

  script:
    - ./chkk -f $manifest_path -t $check_type -s $skip_checks -r $run_checks --continue-on-error=$continue_on_error --show-diff=$show_diff --endpoint http://docker:$endpoint_port
