---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: ratings
spec:
  workloadSelector:
    labels:
      app: nc-pod
  ingress:
  - port:
      number: 26500
      protocol: HTTP
      name: http
    defaultEndpoint: 127.0.0.1:26500
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nc-pod
  labels:
    name: nc-pod
    app: nc-pod
    version: 0.1.0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nc-pod
        version: 0.1.0
    spec:
      containers:
        - name: nc-pod
          image: quay.io/samsung_cnct/nc-pod:latest
          env:
            - name: NC_CMD_ARGS
              value: "-n -k -v -l 127.0.0.1 26500"
          ports:
          - containerPort: 26500
---
apiVersion: v1
kind: Service
metadata:
  name: netcat
spec:
  ports:
  - port: 26500
    protocol: TCP
  selector:
    app: nc-pod
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nc-pod2
  labels:
    name: nc-pod2
    version: 0.1.0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: 0.1.0
    spec:
      containers:
        - name: nc-pod2
          image: quay.io/samsung_cnct/nc-pod:latest
          env:
            - name: NC_CMD_ARGS
              value: "-n -k -v -l 127.0.0.1 26500"
          ports:
          - containerPort: 26500


