apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings-route
spec:
  hosts:
  - s1.default.svc.cluster.local
  http:
  - match:
    - method:
        regex: "test"
      name: 80_default
    route:
    - destination:
        host: s1.default.svc.cluster.local
